name: facial_recognition
description: Um projeto baseado no plugin google_ml_kit focado apenas na parte de deteção de rosto para validação de dados biométricos faciais.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  path_provider: ^2.1.0

  google_mlkit_commons:
  google_mlkit_face_detection:
    path: ../google_mlkit_face_detection
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sgvs/facial_scan.svg
